2nd Order NAE Constraints
PlasmaControl/DESC pull request #1036
Opened 2024-05-24 18:58 UTC by dpanici

- [x] make tests for this
- [x] write out the coefficients in a simpler form (see below)
- [x] add some warning or error for when trying to fix lambda and using asym qsc NAE constraints, since the qsc lambda does not necessarily have zero FSA which can cause the linear constraint projection to error out
- [x] adjust Rlmn Zlmn when shifting lambda on axis for asym #1594 (just making issue for now)

2025-01-21 03:07 UTC, f0uriest requested changes
Haven't gone over all the math in detail, but if you and eduardo both say its correct I'll trust you.

2025-01-21 03:07 UTC, f0uriest commented on desc/objectives/nae_utils.py
> +    Description
don't need this heading

2025-01-21 03:07 UTC, f0uriest commented on desc/objectives/nae_utils.py
> +        qsc (Qsc): pyQsc Qsc object to use as the NAE constraints on the DESC eq
extra indents again

2025-01-21 03:07 UTC, f0uriest commented on desc/objectives/nae_utils.py
> +        follows eqns 30a and 30b in NAE2DESC document
can you include this document somewhere? Could add a folder to docs for developer stuff like this.

2025-01-21 03:07 UTC, f0uriest commented on tests/test_examples.py
> +def test_NAE_QSC_2nd_order_solve():
can you add a test for non-stellarator symmetry?

2025-01-21 07:38 UTC, SebereX requested changes

2025-01-21 07:38 UTC, SebereX commented on desc/objectives/nae_utils.py
> +        - X1phis**2 * ddR0 / 4 / R0**2
@dpanici  @f0uriest  R_2_0, R_2_neg2 and R_2_2 can be simplified collecting terms for faster evaluation. Otherwise implementation of second order looks correct. As Rory said, add the Mathematica file or pdf for reference.

2025-01-21 07:38 UTC, SebereX commented on desc/objectives/nae_utils.py
> +    """
Do you have a test or something like that to check the correct implementation of these coefficients?

2025-01-23 20:28 UTC, dpanici commented on desc/objectives/nae_utils.py
> +    """
None beyond testing a solve with them, I can make one to test at least like the symmetries of each one or something though.

2025-01-27 22:52 UTC, dpanici commented on desc/objectives/nae_utils.py
> +        Lbasis_sin = FourierSeries(N=N, NFP=nfp, sym="sin")
not intended, Im fixing

2025-02-12 21:08 UTC, dpanici commented on tests/test_examples.py
> +def test_NAE_QSC_2nd_order_solve():
I will add a warning/error

2025-02-28 02:01 UTC, f0uriest requested changes

2025-03-04 03:12 UTC, f0uriest submitted a review, later dismissed

2025-03-28 14:18 UTC, SebereX approved these changes

2025-04-01 19:15 UTC, f0uriest approved these changes

2025-04-02 01:44 UTC, merged