Partial derivatives (of the same coordinate system) commute
PlasmaControl/DESC pull request #1068
Opened 2024-06-23 04:04 UTC by unalmis

A few compute functions do a lot of work to compute the same thing as another, sometimes with slightly different math. It's better to just alias them to the other so that there is less math to check as mentioned  [here](https://github.com/PlasmaControl/DESC/pull/648#issuecomment-1718219257).

2024-06-23 14:14 UTC, unalmis commented on desc/compute/_basis_vectors.py
> -            -2 * data["omega_rz"] * data["R_r"] * data["omega_r"]
this is the same as the other existing mixed partial; there's nothing to check here just copy pasted

2024-06-23 21:28 UTC, dpanici requested changes
Good catch, @kianorr has previously implemented an `alias` keyword to the decorator just for this purpose, can you remove the duplicate compute definitions and use the `alias` kwarg to accomplish this instead?

example is here: https://github.com/PlasmaControl/DESC/blob/f7383817d9aee40d54fec1d9a36e685d0cfe7c0c/desc/compute/_metric.py#L1373

2024-06-23 21:29 UTC, dpanici commented
Also maybe in `test_compute_everything` we also compute the aliases? or would that be too much duplicated computation? I am fine either way, as of now this PR works and everything is also tested bc of that test, but with the `alias` method, there won't be a test that the aliased things are computed correctly, idt.

2024-06-24 01:39 UTC, unalmis commented
> Also maybe in `test_compute_everything` we also compute the aliases? or would that be too much duplicated computation? I am fine either way, as of now this PR works and everything is also tested bc of that test, but with the `alias` method, there won't be a test that the aliased things are computed correctly, idt.

i don't think this is worth testing

2024-06-24 01:51 UTC, unalmis commented on desc/compute/_basis_vectors.py
> +    aliases=["e_theta_rrt"],
permutations like e_theta_rtr are connected automatically

2024-06-24 03:00 UTC, unalmis commented
If any of the quantities with an alias in the list of variables [here](https://desc-docs--1068.org.readthedocs.build/en/1068/variables.html) can be discontinuous, then we should undo commit d1863062f4ce83008e29a79e564a9e65eb00688e before merging. (The basis vectors are always continuous, so the jacobian derivatives etc. are too - and i don't think desc can get discontinuous derivatives of |B|)

2024-06-24 13:30 UTC, kianorr commented
> If any of the quantities with an alias in the list of variables [here](https://desc-docs--1068.org.readthedocs.build/en/1068/variables.html) can be discontinuous, then we should undo commit [d186306](https://github.com/PlasmaControl/DESC/commit/d1863062f4ce83008e29a79e564a9e65eb00688e) before merging. (The basis vectors are always continuous, so the jacobian derivatives etc. are too - and i don't think desc can get discontinuous derivatives of |B|)

what do you mean by discontinuous/continuous?

2024-06-24 15:36 UTC, unalmis commented
> > If any of the quantities with an alias in the list of variables [here](https://desc-docs--1068.org.readthedocs.build/en/1068/variables.html) can be discontinuous, then we should undo commit [d186306](https://github.com/PlasmaControl/DESC/commit/d1863062f4ce83008e29a79e564a9e65eb00688e) before merging. (The basis vectors are always continuous, so the jacobian derivatives etc. are too - and i don't think desc can get discontinuous derivatives of |B|)
> 
> what do you mean by discontinuous/continuous?

For example, the components of B tangential to a surface current will be discontinuous. It's not as obvious whether interchanging partial derivatives is valid near discontinuities, and one would have to do math or seek weaker conditions to justify it. I don't think we need to worry about this - all the derivatives of B are compositions of continuous functions as we have implemented. I was mainly just documenting the assumptions for commit [d186306](https://github.com/PlasmaControl/DESC/commit/d1863062f4ce83008e29a79e564a9e65eb00688e) in case anyone changes stuff in future.

2024-06-24 20:29 UTC, dpanici approved these changes

2024-06-25 16:28 UTC, ddudt approved these changes

2024-06-25 21:10 UTC, merged