Remove basis kwarg from _compute function calls in magnetic field classes
PlasmaControl/DESC pull request #1137
Opened 2024-07-20 02:26 UTC by dpanici

- Fixes some leftover basis args inside of `_compute` calls, which now throw an error since that function only returns `rpz` quantities

2024-07-20 04:52 UTC, f0uriest approved these changes

2024-07-22 01:17 UTC, ddudt requested changes
If this is wrong on master but wasn't being covered, we should add tests.

2024-07-23 13:40 UTC, dpanici commented
> If this is wrong on master but wasn't being covered, we should add tests.

Tests caught a bug, thanks for making me write them

2024-07-23 20:10 UTC, f0uriest approved these changes

2024-07-24 02:28 UTC, ddudt approved these changes

2024-07-24 16:02 UTC, YigitElma approved these changes

2024-07-24 16:11 UTC, merged