Throw error for when `Curve` is used for coil objectives
PlasmaControl/DESC pull request #1141
Opened 2024-07-23 20:25 UTC by kianorr

Resolves #1020 

The given example in #1020 uses a `FourierPlanarCurve` which actually results in a list of numpy arrays being created after going through `tree_flatten`.

If there is a `Curve` object in a `CoilSet` then there are already checks in the `CoilSet` class that throw an error.

2024-07-23 22:29 UTC, f0uriest commented
could do something like:
```python
for coil in coils:
    errorif(not isinstance(coil, _Coil),
            TypeError,
            f"Expected object of type Coil, got {type(coil)}",
)
```

that way it actually says what the offending member is.

2024-08-20 18:36 UTC, dpanici requested changes
add a test

2024-08-21 22:04 UTC, f0uriest approved these changes

2024-08-22 15:53 UTC, dpanici approved these changes

2024-08-28 20:00 UTC, merged