Figures for Surface Current and Coil-Cutting Paper
PlasmaControl/DESC pull request #1307
Opened 2024-10-17 01:23 UTC by dpanici

Small thing which I think is fine: the torus knots rely on #844 to make the figures, which I note in the script.

2024-10-18 08:03 UTC, rahulgaur104 commented
```
        plt.figure()
        theta_grid = np.linspace(0, 2 * np.pi, 300)
        zeta_grid = np.linspace(0, 2 * np.pi, 300)
        grid = LinearGrid(rho=1.0, theta=theta_grid, zeta=zeta_grid)
        fig = plot_3d(eq, name="|B|", grid=grid)

        fig.update_traces(
            colorbar=dict(
                tickfont=dict(size=58),  # Adjust the size value as needed
                title_font=dict(size=58),  # Adjust the size value as needed
            )
        )

        fig.update_layout(font=dict(size=18, color="black", family="Arial, sans-serif"))

        config = {
            "toImageButtonOptions": {
                "filename": f"modB_3d_{keyword}_{legend}",
                "format": "svg",
                "scale": scale,
            }
        }

        save_path_html = os.getcwd() + f"/3D_modB/modB_3d_{keyword}_{legend}.html"
        fig.write_html(
            save_path_html, config=config, include_plotlyjs=True, full_html=True
        )

        # save_path_png = os.getcwd() + f"/3D_modB/modB_3d_{keyword}_{legend}.png"
        # fig.write_image(save_path_png, scale=scale)
        plt.close()
```
Something you can use to increase the font size of the colorbar for the 3D plots and save a svg (high resolution and small file size).

2026-06-25 17:39 UTC, daniel-dudt requested changes
Remove the figure .png files, the script that generates them is enough.

2026-07-13 23:15 UTC, YigitElma approved these changes

2026-07-16 18:38 UTC, daniel-dudt approved these changes

2026-07-16 18:38 UTC, daniel-dudt commented on publications/panici2025/coil_paper/figures/figure_surface_integral.pptx
I don't love tracking a PowerPoint file with git, but I'll allow it if it's necessary.

2026-07-17 17:17 UTC, merged