Add num_turns attribute to coils
PlasmaControl/DESC pull request #1311
Opened 2024-10-19 00:16 UTC by dpanici

- Adds `num_turns` attribute to coilsets, which effectively just multiplies the current in biot-savart. Would be useful as well for magnetic diagnostics where the number of turns in the coil matters when computing the flux through the loop (this is an approach to put that info on the Coil side, I guess we could choose to put that information when whatever objective for that coil diagnostic is made... but it feels cleaner to me to have it be a coil attribute)

2024-10-19 01:54 UTC, dpanici commented
This might not be needed once we decide on #1169 actually, if we have some sort of nfilaments thing there...

2024-10-23 17:07 UTC, dpanici commented
Better to do a subclass of curve instead of coil for stuff like Rogowski etc

2025-01-31 22:15 UTC, ddudt requested changes

2025-01-31 22:15 UTC, ddudt commented on desc/coils.py
> +        new = setdefault(new, 1, new)
What is the purpose of this? Wouldn't this prevent someone from setting the current to 0, since 0 = False and so it would get replaced with the default value of 1?

2025-01-31 22:15 UTC, ddudt commented on desc/coils.py
> -            name for this coil
Why delete this? I think it should still say ` Name for this coil.` like we have for all the similar methods of other coil classes.

2025-01-31 22:15 UTC, ddudt commented on desc/coils.py
> +        name for this coil
I prefer proper punctuation in our doc strings, I think we do that in most cases

2025-01-31 22:17 UTC, ddudt commented on desc/coils.py
> +        new = setdefault(new, 1, new)
I think you might have meant to do `new = setdefault(new, 1)`

2025-02-05 21:25 UTC, dpanici commented on desc/coils.py
> +        new = setdefault(new, 1, new)
check if can set current to 0

2025-02-05 23:57 UTC, dpanici commented on desc/coils.py
> +        name for this coil
we are pretty inconsistent even in this file

2025-02-09 00:12 UTC, YigitElma approved these changes

2025-02-10 17:43 UTC, f0uriest approved these changes

2025-02-10 22:30 UTC, ddudt approved these changes

2025-02-11 15:34 UTC, merged