Update stage 2 optimization tutorial weights
PlasmaControl/DESC pull request #1342
Opened 2024-10-31 15:45 UTC by dpanici

Resolves #1341

2024-11-01 17:03 UTC, YigitElma approved these changes

2024-11-28 17:30 UTC, YigitElma requested changes
I believe there are some remaining commented parts left you used for comparison.

I added some missing semicolons.

2024-12-02 19:31 UTC, YigitElma commented
> View / edit / reply to [this conversation](https://app.reviewnb.com/PlasmaControl/DESC/pull/1342/discussion/#comment-2506556666) on ReviewNB
> 
> _YigitElma commented on 2024-11-28T17:28:55Z_ ----------------------------------------------------------------
> 
> Line #18.    def make_vac_coil_obj(eq, coilset, weights_dict):
> You say you will use the dictionary to change the weights but you manually put them. Probably you were experimenting and forgot?

Can you also fix this?

2024-12-02 21:52 UTC, YigitElma approved these changes

2024-12-03 18:53 UTC, f0uriest approved these changes

2024-12-03 19:24 UTC, merged