Utility functions for initializing coils for stage 2 optimization
PlasmaControl/DESC pull request #1361
Opened 2024-11-13 01:27 UTC by f0uriest

Resolves #1182 
Resolves #1183

2024-11-13 19:58 UTC, dpanici requested changes
I think some of the outer saddle coils are linking the modular coils for the finite beta example

2024-11-13 20:02 UTC, dpanici commented on desc/coils.py
> +
Possibly add a note about checking that they do not intersect the plasma? though this is a common sense thing to check before optimization I guess

2024-11-13 20:03 UTC, dpanici commented on desc/coils.py
> +
note on the initial resoution and changing the resolution as well?

2024-11-14 04:53 UTC, f0uriest commented
Can someone try running the updated notebook locally? The test is failing but everything seems fine locally for me.

2024-11-15 06:22 UTC, dpanici commented
> Can someone try running the updated notebook locally? The test is failing but everything seems fine locally for me.

I also ran locally with no issues. Maybe a memory issue with the CI runner?

2024-11-25 04:21 UTC, dpanici commented
This should be either combined or ahead/behind #1342 as they modify the same notebook. I would be fine to just make those changes into this PR and close the other one tbh to avoid the notebook merge conflict headaches

2024-11-25 15:58 UTC, dpanici commented
I don't understand why for this PR tests fails due to too large of a diff, but for #1342 the tests are able to run?

2024-12-03 21:30 UTC, dpanici commented
> I don't understand why for this PR tests fails due to too large of a diff, but for #1342 the tests are able to run?

This seems fixed now? weird

2024-12-03 22:09 UTC, dpanici commented
Sorry, forgot I had not meant to merge in #1342 before this one. I can deal with the merge conflict if you want, I think using `nbdime` would make it easier so I can try that out

2024-12-15 23:02 UTC, dpanici approved these changes
I merged the notebook with master, it should be good now

2024-12-17 21:17 UTC, f0uriest commented
> I merged the notebook with master, it should be good now

Did you also re-run it? Or just merge the old version? I don't think the previous one included all the recent changes

2024-12-18 18:30 UTC, dpanici commented
@dpanici rerun this

2024-12-18 18:30 UTC, dpanici requested changes
rerun notebook

2024-12-18 20:24 UTC, dpanici approved these changes

2025-01-20 19:40 UTC, sinaatalay approved these changes
Two functions have been added to `desc.coils` (`initialize_modular_coils` and `initialize_saddle_coils`), and their tests have been written. I couldn't find any spelling errors in docs/docstrings. I don't fully understand what's happening inside the functions, but their tests seem reliable to me, and they pass. I think's this PR is good to go.

2025-01-20 20:15 UTC, merged