Rc/transforms
PlasmaControl/DESC pull request #1405
Opened 2024-11-21 04:12 UTC by f0uriest

2024-12-18 18:25 UTC, dpanici commented
replace at axis with 0.0 for quantities we know must be the case

2025-01-28 21:37 UTC, f0uriest commented on tests/test_plotting.py
> -        return fig
newer versions of pytest complain if tests return something that isn't used

2025-01-30 22:05 UTC, dpanici submitted a review, later dismissed

2025-02-03 06:08 UTC, unalmis requested changes
basis.py comments optional; please review other comments

2025-02-05 22:16 UTC, f0uriest commented on desc/basis.py
> +            self._inverse_N_idx,
I think in the case of stellarator symmetry its no longer a strict tensor product basis, so we still need the full modes array

2025-02-05 22:20 UTC, f0uriest commented on desc/basis.py
> +        toroidal = toroidal[zoutidx][:, noutidx]
I don't think so, and in the worst case this still shouldn't be a memory bottleneck. We can't use outer products in many cases due to symmetry in the basis or non mesh grids.

2025-02-05 22:22 UTC, f0uriest commented on desc/grid.py
> +            dz = zeta_period * np.ones_like(z)
I thought dz was the actual spacing, not the weight (which would need a factor of NFP)?

2025-02-05 22:50 UTC, unalmis approved these changes

2025-02-12 15:42 UTC, dpanici submitted a review, later dismissed

2025-02-12 19:00 UTC, unalmis approved these changes

2025-02-12 19:02 UTC, unalmis approved these changes

2025-02-12 21:31 UTC, ddudt commented on desc/grid.py
> +            self._fft_poloidal = (not endpoint) and (not self.sym)
Won't this still evaluate to `fft_poloidal = True` even if the nodes are non-uniform?

2025-02-12 21:31 UTC, ddudt commented on desc/grid.py
> +            self._fft_toroidal = not endpoint
see previous comment

2025-02-12 22:06 UTC, merged