Update notebooks with new stopping criteria
PlasmaControl/DESC pull request #1425
Opened 2024-12-04 04:42 UTC by f0uriest

Updates all the notebooks with new stopping criteria (and misc other changes since they were last ran forever ago).

- Ballooning notebook waiting on #1424 
- Coil optimization notebook waiting on #1361 

Resolves #1423

2024-12-14 04:14 UTC, YigitElma requested changes
For CI's sake, we might need to reduce the maxiter for ballooning notebook.

2024-12-20 07:23 UTC, YigitElma commented
I am note sure if it is caused a difference but, once we are at, should we rerun them since #1363 ? Let me know, I can run them again!

2025-01-03 21:32 UTC, YigitElma approved these changes

2025-01-07 00:41 UTC, dpanici approved these changes

2025-01-07 00:52 UTC, merged