`CoilConvexity` objective
PlasmaControl/DESC pull request #1485
Opened 2024-12-20 23:13 UTC by ddudt

A scalar version of convexity for a curve: $\int \kappa |\partial_s \mathbf{x}| ds = 2 \pi$

Similar to our existing `CoilCurvature` objective, which is signed to indicate convexity.

2025-01-20 19:48 UTC, dpanici commented on desc/objectives/_coils.py
> +        errorif(
I don't love this, can you instead do something like giving the CoilConvexity objective a `self._endpoint` attribute, and in this build check if hasattr(self,_endpoint) and usethat, else set it to False.

Then have this error check statement be after the `super.build()` statement inside of `CoilConvexity`'s build method

2025-01-20 19:50 UTC, dpanici commented on desc/objectives/_coils.py
> +    """Coil convexity.
make it more clear that it is targeting that this objective is targeting to make the coil convex by making the that integral quantity minus 2pi = 0, that way the target of this objective being zero makes sense.

As is, it is ambiguous as to whether one should make the target 2pi or 0.

2025-01-20 19:52 UTC, dpanici commented on desc/objectives/_coils.py
> +        name="coil convexity",
should be "coil convexity error"  I think, since you are subtracting by 2pi.

2025-01-20 19:55 UTC, dpanici submitted a review, later dismissed
- give a `self._endpoint` attribute to `CoilConvexity` to be True
- check for this attribute in `_CoilObjective.build` to decide if `endpoint` should be true or not (False by default if `hasattr(self._endpoint)` is False
- move errorif statement to after `super.build()` in `build` of `CoilConvexity`
- make docstring clearer for `CoilConvexity`
- Fix docs

2025-01-22 20:47 UTC, dpanici commented
Call it `IntegratedCurvature`

2025-01-28 19:30 UTC, f0uriest requested changes

2025-01-28 19:30 UTC, f0uriest commented on desc/objectives/_coils.py
> +class IntegratedCurvature(_CoilObjective):
Do we want to include the word `Coil` somewhere in the name? (ie to distinguish from the integrated curvature of the plasma boundary or something)
 `IntegratedCoilCurvature`? `CoilIntegratedCurvature`? `CoilCurvatureIntegrated`?

2025-01-28 19:30 UTC, f0uriest commented on desc/objectives/_coils.py
> +                trapezoid(
I think you can get the same thing if you leave off the endpoint and do `(curvature*x_s*ds).sum()`. The integrand is periodic so the endpoint and start are the same.

2025-01-28 19:30 UTC, f0uriest commented on desc/objectives/_coils.py
> +    If a curve is convex, then the following condition must be true: ∫ κ |∂ₛx| ds = 2π.
should mention what kappa, x_s etc mean here

2025-01-28 19:30 UTC, f0uriest commented on tests/test_objective_funs.py
> +        IntegratedCurvature,
keep this alphabetized

2025-01-28 19:30 UTC, f0uriest commented on tests/test_objective_funs.py
> +            IntegratedCurvature,
keep this alphabetized

2025-01-28 19:30 UTC, f0uriest commented on tests/test_objective_funs.py
> +        IntegratedCurvature,
keep this alphabetized

2025-01-28 19:30 UTC, f0uriest commented on tests/test_objective_funs.py
> +            IntegratedCurvature,
keep this alphabetized

2025-01-28 21:57 UTC, ddudt commented on desc/objectives/_coils.py
> +                trapezoid(
This is slightly less accurate then the trapezoid integration (`atol=2e-5` vs `atol=1e-6` at the grid resolution used in the tests) but I still like this change for the simplicity.

2025-01-28 21:58 UTC, YigitElma commented on desc/objectives/_coils.py
> +class IntegratedCurvature(_CoilObjective):
Although I like `CoilIntegratedCurvature` more, for sake of not having l and capital i next to each other, I vote for `CoilCurvatureIntegrated`.

2025-01-28 21:58 UTC, YigitElma commented on desc/objectives/_coils.py
> +    """Curvature integrated along a coil.
```suggestion
    """Curvature integrated along each coil.
```

2025-01-28 21:58 UTC, YigitElma commented on desc/objectives/_coils.py
> +            Dictionary of constant data, eg transforms, profiles etc. Defaults to
```suggestion
            Dictionary of constant data, e.g. transforms, profiles etc. Defaults to
```

2025-01-28 21:58 UTC, YigitElma commented on desc/objectives/_coils.py
> +                    jnp.abs(dat["curvature"]) * safenorm(dat["x_s"], axis=1), dat["s"]
I don't know the actual formula but from the integral, I didn't understand why there `jnp.abs(kappa)` here? Can you explain?

2025-01-28 21:58 UTC, YigitElma commented on tests/test_objective_funs.py
> +                    grid=LinearGrid(N=int(5 + 3 * res), endpoint=objective._endpoint),
`CoilSetLinkingNumber` and `CoilSetMinDistance` are not a subclass of `_CoilObjective`, so don't have `_endpoint` attribute.

2025-01-28 22:03 UTC, ddudt commented on desc/objectives/_coils.py
> +                    jnp.abs(dat["curvature"]) * safenorm(dat["x_s"], axis=1), dat["s"]
We want to integrate the unsigned curvature, but our compute quantity `"kappa"` is the signed curvature, where the sign denotes the local convexity.

2025-01-28 22:09 UTC, YigitElma commented on desc/objectives/_coils.py
> +                    jnp.abs(dat["curvature"]) * safenorm(dat["x_s"], axis=1), dat["s"]
Thanks, the explanation in the docs makes it clear now.

2025-01-28 22:10 UTC, YigitElma approved these changes

2025-01-28 23:37 UTC, YigitElma submitted a review, later dismissed

2025-01-29 02:13 UTC, f0uriest approved these changes

2025-01-29 02:16 UTC, f0uriest commented on desc/objectives/_coils.py
> +    If a curve is convex, then the following condition must be true: ∫ κ |∂ₛx| ds = 2π
needs to be `||∂ₛx||` to avoid rst issues

2025-01-29 22:02 UTC, f0uriest approved these changes

2025-01-29 22:28 UTC, YigitElma approved these changes

2025-01-29 23:32 UTC, merged