Ku/bounce alpha
PlasmaControl/DESC pull request #1494
Opened 2024-12-25 11:18 UTC by unalmis

Enable tracking multiple fieldlines with Bounce2D and simplify analyzing drift over alpha as requested by a few people.

2024-12-25 11:28 UTC, unalmis commented on desc/compute/_fast_ion.py
> +            return jnp.sum(v_tau * gamma_c**2, axis=-1).mean(axis=-2)
the tldr is to replace this mean over the alpha axis with the logic on `gh/Gamma_c`.

2025-01-02 19:23 UTC, dpanici commented on desc/compute/_fast_ion.py
> +            return jnp.sum(v_tau * gamma_c**2, axis=-1).mean(axis=-2)
which logic from that branch specifically?

2025-01-02 19:39 UTC, unalmis commented on desc/compute/_fast_ion.py
> +            return jnp.sum(v_tau * gamma_c**2, axis=-1).mean(axis=-2)
for gamma_alpha and gamma_d you have to perform a different operation over the poloidal angle than `.mean()`

2025-01-02 19:53 UTC, dpanici commented on desc/integrals/quad_utils.py
> +    w = jnp.pi * jnp.sin(t) / (deg + 1)
why the removal of the abs? shouldnt this be positive?

2025-01-02 19:54 UTC, unalmis commented on desc/integrals/quad_utils.py
> +    w = jnp.pi * jnp.sin(t) / (deg + 1)
the domain `t` makes this positive regardless. less operations means less gradients so less memory

2025-01-02 19:58 UTC, dpanici commented on tests/test_fast_ion.py
> +    rho = np.linspace(1e-12, 1, 10)
what changed at 0? or was it just analytically 0 before and you want to check it is not blowing up?

2025-01-02 20:02 UTC, unalmis commented on tests/test_fast_ion.py
> +    rho = np.linspace(1e-12, 1, 10)
It's zero analytically on axis, which I confirmed when I wrote the quantity. The reason for the change is here
- For the 2D methods, including zero will compute the axis limits of the dependencies, which will slow down the tests for no reason.
- For the 1D methods, `get_rtz_grid` makes a jitable grid by default which [moves the nodes to 1e-12](https://github.com/PlasmaControl/DESC/blob/6b069f3f2994de2f0297dce876b223eb8aedd6a1/desc/grid.py#L764) anyway.

2025-01-02 20:11 UTC, dpanici requested changes
just the one comment on the plotting when grid has multiple rho for check_points, either
- change check_points to have a rho/alpha label somewhere in the title
- or just make a comment in that notebook that they are at different rho, same alpha, and make a TODO for changing check_points

2025-01-03 00:30 UTC, unalmis commented
<p>Yes typically there is a finer structure near axis, but the integration domain is also much smaller (max B - min B is small)</p><p> </p>

---

 <a href='https://app.reviewnb.com/PlasmaControl/DESC/pull/1494/discussion/#comment-2568311789'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2025-01-03 02:42 UTC, dpanici approved these changes

2025-01-08 19:00 UTC, rahulgaur104 commented
Here's what I am running to test this

```python

#!/usr/bin/env python3
import numpy as np
from desc.examples import get
from desc.grid import LinearGrid
from matplotlib import pyplot as plt
from desc.integrals import Bounce2D

import pdb

eq = get("W7-X")

rho = 0.5
X, Y = 16, 32
theta = Bounce2D.compute_theta(eq, X, Y, rho)
num_transit = 3
num_well = 10 * num_transit
num_quad = 32

Y_B = 32

N_alpha = int(4)
num_pitch = int(32)

alpha_arr = np.linspace(0, 2*np.pi, N_alpha)
grid = LinearGrid(rho=rho, M=eq.M_grid, N=eq.N_grid, NFP=eq.NFP, sym=False)

data = eq.compute(
            "Gamma_c",
            grid=grid,
            theta=theta,
            Y_B=Y_B,
            num_transit=num_transit,
            num_well=num_well,
            num_quad=num_quad,
            num_pitch=num_pitch,
            alpha =alpha_arr,
            # Can also specify ``pitch_batch_size`` which determines the
            # number of pitch values to compute simultaneously.
            # Reduce this if insufficient memory. If insufficient memory is detected
            # early then the code will exit and return ε = 0 everywhere. If not detected
            # early then typical OOM errors will occur.
            )

pdb.set_trace()

```
but the shape of gamma_c is still (1, num_pitch)

2025-01-08 19:06 UTC, rahulgaur104 approved these changes

2025-01-08 20:27 UTC, rahulgaur104 commented
Codecov short by 0.65%. Merging now.

2025-01-08 20:27 UTC, merged