Implement Symbolic Recursive Integration for Dommaschk
PlasmaControl/DESC pull request #1496
Opened 2024-12-26 08:14 UTC by dpanici

Resolve #1467 , #1278 

Changes implementation of Dommaschk potentials to use `sympy` and symbolic integration to recursively compute the potentials with symbolic algebra, as well as symbolically take the gradient of the potential. I then use the `sympy.lambdify` function to turn this gradient into a jax expression usable with our other machinery like the poincare plotting.

TODO
- [ ] try to use lambdify on the potential function itself, and have it be lambdified w.r.t. each of its params, in order to allow for the resulting function to be differentiated w.r.t. both the cyl coords AND the coeffs and params.

Notes
------

I've found that using sympy and symbolic integration to use the recursive form of the Dommaschk potentials to be a much more accurate way to use them (accurate as in, recreating poincare plots from the IPP report linked [here](https://pure.mpg.de/rest/items/item_2132035_1/component/file_2132034/content))

Previous implementation was non-recursive and suffered from issues for certain more complex potentials, which were either due to numerical issues in the algorithm (precision issues) or due to an incorrect implementation on my part (which I never was able to track down). Either way, this symbolic method seems to work much better. 

Only downside is as of right now I am unsure how to get this to work in a way that would also let this field class be Optimizable (as of now on this PR, we cannot differentiate its compute magnetic field fxn wrt the params of the field, though on master the class was not setup to do this either).
This does not remove any functionality as far as optimizing with this field goes, since it never had it to begin with, but it does make the fitting function broken right now. I can fix it to compute things by looping over single mode contributions to the field, but it would be cleaner to figure out a way to get the function differentiable wrt params again.

2025-01-08 18:47 UTC, dpanici commented on desc/magnetic_fields/_dommaschk.py
> +import sympy as sp
import this stuff in backend not here

2025-01-21 02:54 UTC, f0uriest requested changes

2025-01-21 02:54 UTC, f0uriest commented on desc/backend.py
> +import sympy as sp  # noqa: F401
i don't think this needs to be in backend, is there any reason we don't just import it normally where its needed?

2025-01-21 02:54 UTC, f0uriest commented on desc/magnetic_fields/_dommaschk.py
> +        # TODO: Add REGCOIL-like option to perform a least squares minimization
prefer to make issues for these rather than TODO in source

2025-01-21 02:54 UTC, f0uriest commented on desc/magnetic_fields/_dommaschk.py
> +        # TODO: does the sym hold if the eq is not "centered" about R=1?
prefer to make issues for these rather than TODO in source

2025-01-21 02:54 UTC, f0uriest commented on desc/magnetic_fields/_dommaschk.py
> +        t0 = time.time()
use `desc.utils.Timer` for this so all the timing info is done in one place

2025-01-21 02:54 UTC, f0uriest commented on desc/magnetic_fields/_dommaschk.py
> +        t0 = time.time()
use desc.utils.Timer for this so all the timing info is done in one place

2025-01-21 02:54 UTC, f0uriest commented on desc/magnetic_fields/_dommaschk.py
> +            print(f"Max Residual: {jnp.max(abs(res_at_pts)):1.4e} T")
max _absolute_ residual, same for min & mean

2025-01-21 02:54 UTC, f0uriest commented on desc/magnetic_fields/_dommaschk.py
>  def dommaschk_potential(R, phi, Z, ms, ls, a_arr, b_arr, c_arr, d_arr, B0=1):
the arguments to this are now expected to be sympy variables, not numpy or jax arrays right? Should update the docstring

2025-01-21 02:54 UTC, f0uriest commented on tests/test_magnetic_fields.py
> +    ms = [
if you want you can turn off black for these sections so it won't put everything on its own line: https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#ignoring-sections

2025-01-21 23:07 UTC, dpanici commented on desc/backend.py
> +import sympy as sp  # noqa: F401
I had moved it just to be in backend but I can move it back. Just thought I remembered someone saying we should import stuff like this in backend.

2025-01-22 21:45 UTC, f0uriest approved these changes

2025-01-22 22:29 UTC, dpanici commented
Moving notes to separate comment so it is not in PR commit comment

Notes
------
I've found that using sympy and symbolic integration to use the recursive form of the Dommaschk potentials to be a much more accurate way to use them (accurate as in, recreating poincare plots from the IPP report linked [here](https://pure.mpg.de/rest/items/item_2132035_1/component/file_2132034/content), which previously I failed to find any flux surface using the nonrecursive algorithm)

Previous implementation was non-recursive and suffered from issues for certain more complex potentials, which were either due to numerical issues in the algorithm (precision issues) or due to an incorrect implementation on my part (which I never was able to track down). Either way, this symbolic method seems to work much better.

2025-01-24 20:01 UTC, YigitElma requested changes

2025-01-24 20:01 UTC, YigitElma commented on tests/test_magnetic_fields.py
> +    """Test can get flux surfaces from W7-AS Dommashk coefficients."""
```suggestion
    """Test getting flux surfaces from W7-AS Dommaschk coefficients."""
```

2025-01-24 20:16 UTC, dpanici commented on desc/magnetic_fields/_dommaschk.py
>          X = jnp.asarray(X)
this is capital X, not lowercase x, but ok yea I can change that it is nbd

2025-01-27 15:06 UTC, f0uriest approved these changes

2025-01-27 15:15 UTC, YigitElma approved these changes

2025-01-27 21:57 UTC, merged