`FourierXYCurve` and `FourierXYCoil` classes
PlasmaControl/DESC pull request #1504
Opened 2024-12-30 19:28 UTC by ddudt

Adds a new parameterization for planar curves/coils. Instead of representing $r(\theta)$ as a Fourier series like the `FourierPlanarCurve`, this represents $X(\theta)$ and $Y(\theta)$ as Fourier series where $r = \sqrt{X^2 + Y^2}$. 

There are some simple coil shapes like an ellipse that cannot be perfectly represented with the `FourierPlanarCoil` class (at finite resolution). This parameterization can represent more coil geometries, at the cost of more optimization parameters and the possibility of self-intersecting curves.

2025-03-05 20:17 UTC, dpanici commented
Add symmetry to FourierSeries basis class and use here to delete the n=0 mode

2025-04-15 03:24 UTC, YigitElma commented on desc/geometry/curve.py
> +    X_n : array-like
I guess it doesn't matter if the user gives n=0 modes or not, the shape is the same, right?

2025-04-15 03:24 UTC, YigitElma commented on desc/geometry/curve.py
> +        N = check_nonnegint(N, "N")
Since N cannot be 0, would `check_posint()` be better?

2025-04-15 21:27 UTC, dpanici commented on desc/basis.py
> +        * ``'n0'`` for no n=0 mode
I don't love this name. I agree that having a basis that lacks a zero mode is useful, but can we be more verbose and say like `"no n=0"` or something?

2025-04-15 21:29 UTC, dpanici commented on desc/geometry/curve.py
> +        R_basis = FourierSeries(N=N, NFP=NFP, sym="cos" if sym else False)
was this incorrect before then?

2025-04-15 21:30 UTC, dpanici commented on desc/geometry/curve.py
> +        mode numbers associated with X_n and Y_n.
can you say the default assumption is [-X_n.size//2 , X_n.size//2], with the n=0 mode included even tho it will be taken out later?

2025-04-15 21:40 UTC, dpanici commented on desc/transform.py
> +        self.fft_index = np.atleast_1d(np.squeeze(self.num_n_modes * row + col))
can you explain this change?

2025-04-15 21:41 UTC, dpanici requested changes
I don't really like `n0` as the new basis sym name, can it be more verbose?

left a question or two as well

2025-04-16 16:44 UTC, ddudt commented on desc/geometry/curve.py
> +        R_basis = FourierSeries(N=N, NFP=NFP, sym="cos" if sym else False)
Yes I think it was. `FourierSeries` has no `sym=True` option, so we probably just never tested that case.

2025-04-16 21:01 UTC, ddudt commented on desc/geometry/curve.py
> +    X_n : array-like
The user should not be giving n=0 modes, you can't give coefficients that are not in the basis.

2025-04-16 21:07 UTC, ddudt commented on desc/geometry/curve.py
> +    X_n : array-like
Should we throw a warning in this case if the user passes in a n=0 mode? Another option is that we could add the n=0 coefficients to the `center` parameter, but then we are overwriting the user inputs. I would rather force the user to give self-consistent inputs.

2025-04-17 13:33 UTC, dpanici requested changes
make docstring of new curve class clearer for what it expects when `modes` is not explicitly passed in (no n0 mode is assumed, modes go from from [-X_n.size//2, X_n.size//2] but assuming n=0 is skipped)

2025-04-17 20:08 UTC, ddudt commented on desc/geometry/curve.py
> +    X_n : array-like
@YigitElma @dpanici What are your opinions on how to handle the case if the user inputs the n=0 mode? Options:

1. User should not give the n=0 coefficient, will error if they do (present code)
2. Throw a warning if the user does give the n=0 coefficient, saying that it is being ignored (I think this is my vote)
3. Allow the user to give the n=0 coefficient, and add it to the `center` input (more general but also more complicated)

2025-04-18 00:18 UTC, f0uriest commented on desc/geometry/curve.py
> +    X_n : array-like
i don't see it throwing an error if `modes` includes n=0 currently? I'd be in favor of this, or warning and dropping it.

2025-04-21 04:45 UTC, YigitElma commented on desc/geometry/curve.py
> +    X_n : array-like
I also like to drop the n=0 modes (I think they are already ignored), but additionally to throw a warning/error like
```
Ignoring n=0 modes. Please explicitly change the center argument if you are trying to shift the center.
```

2025-04-23 20:49 UTC, ddudt commented on desc/geometry/curve.py
> +        mode numbers associated with X_n and Y_n.
FYI the default value for `modes` now handles both cases: 

- If `len(X_n)` is odd, then it assumes the n=0 mode is included like the other curve classes but gets ignored. 
- If `len(X_n)` is even, then it assumes the n=0 mode is not included since it is unused for this class.

2025-05-10 21:25 UTC, dpanici commented
I think changes made to `FourierPlanarCurve.from_values` generalizing its curve parmeter actually break the curve fitting, as you allow for an arbitrary curve parameter (not the polar angle) but we assume the polar angle in the compute functions for it (i.e. we say X=r cos(s) and Y = rsin(s) which implies tan(s) = Y/X, which is not used/enforced in the `from_values` method)

```python
import numpy as np
from desc.coils import FourierPlanarCoil, FourierXYZCoil, FourierRZCoil
from desc.grid import LinearGrid

coil_XYZ = FourierXYZCoil(
    current=1e6, X_n=[0, 10, 1],
    Y_n=[-2, 0, 0],
    Z_n=[0, 0, 0]
)
coil_planar = coil_XYZ.to_FourierPlanar(N=10)
d_xyz = coil_XYZ.compute(["x"],basis="xyz")
d_planar = coil_planar.compute(["x"],basis="xyz")

import matplotlib.pyplot as plt
plt.plot(d_xyz["x"][:,0], d_xyz["x"][:,1], label="xyz")
plt.plot(d_planar["x"][:,0], d_planar["x"][:,1],"--", label="planar fit")
plt.legend()
plt.xlabel("x")
plt.ylabel("y")
plt.axis("equal")
```
![image](https://github.com/user-attachments/assets/464dfbde-b206-43bb-8226-6721ed65fd49)
![image (1)](https://github.com/user-attachments/assets/a7d89ffe-efd2-4090-9c1d-2f882dd3065a)

2025-05-10 21:30 UTC, dpanici requested changes
undo the changes to `FourierPlanarCurve.from_values` which allow arbitrary curve parameter, as we cannot allow that given the way `"x"` is computed assuming that `tan(s) = Y/X` in the plane which enforces a specific choice of curve parameter

2025-05-16 20:00 UTC, dpanici commented
was the update for master compute data only for the `FourierPlanarCurve` stuff?

2025-05-16 20:41 UTC, ddudt commented
> was the update for master compute data only for the `FourierPlanarCurve` stuff?

No. This adds new classes and `test_compute_everything` checks the compute quantities for each class. So I had to add the data for those new classes.

2025-05-19 20:53 UTC, dpanici commented on desc/coils.py
> +    the polar angle theta.
```suggestion
    an arbitrary curve parameter ``s``
```

2025-05-19 20:54 UTC, dpanici commented on desc/geometry/curve.py
> +    and Fourier series defining the X and Y coordinates in the plane.
mention that the Fourier series is in an arbitrary angle

2025-05-19 20:54 UTC, dpanici commented on desc/geometry/curve.py
> +        """Center of planar curve polar coordinates."""
they are not polar coordinates right? not for this one

2025-05-19 20:59 UTC, dpanici commented on desc/objectives/_coils.py
> +    and ``FourierXYCoil`` which have a single unique parameterization
not correct about the FourierXYCoil

2025-05-19 21:09 UTC, dpanici commented on tests/test_coils.py
> +    coil_planar2 = coil_XYZ.to_FourierXY(N=1)
Since `FourierXY` uses an arbitrary angle, idt this is actually an issue. But am fine with keeping the test

2025-05-19 21:13 UTC, dpanici commented on desc/geometry/curve.py
> +        # normal
Question for this curve class: 

technically it works totally fine if the curve orientation and the normal direction are opposite (in the sense that you can have a curve which is oriented left-handed w.r.t. the normal vector). Unless we include a line like Ryan has in the `from_values` of `FourierPlanarCurve` this will be allowed. This does not break anything as far as I can tell. Just want to note this as could be slightly counterintuitive

2025-05-19 21:14 UTC, dpanici requested changes
some minor changes requested. Also see note on the normal vector for FourierXY, Idt it matters but should think about for a sec

2025-05-19 21:23 UTC, YigitElma commented on desc/geometry/curve.py
> +        """Center of planar curve polar coordinates."""
```suggestion
        """Center of planar curve in `self.basis` coordinates."""
```

2025-05-19 21:23 UTC, YigitElma commented on desc/geometry/curve.py
> +        """Center of planar curve polar coordinates."""
Or just delete that part as in `self.normal`s doc.

2025-05-19 21:54 UTC, ddudt commented on desc/geometry/curve.py
> +        # normal
Hmm good point. There is a "right-handed" orientation wrt the normal vector, but it doesn't actually affect any of the computations. The only thing that matters is the physical direction of the current flowing in the coil. I think we should keep it general so that the user can choose the orientation they find the most convenient (e.g., they might want a "left-handed" curve if that allows them to make the current positive instead of negative.)

2025-05-19 22:09 UTC, YigitElma approved these changes

2025-05-22 15:53 UTC, dpanici approved these changes

2025-05-22 17:17 UTC, YigitElma approved these changes

2025-05-22 18:55 UTC, merged