Increase precision of np.std in utils.py to avoid numerical errors fo…
PlasmaControl/DESC pull request #359
Opened 2022-12-16 23:50 UTC by dpanici

…r large arrays
solves #358

2022-12-17 19:02 UTC, f0uriest commented
Would a better solution be to avoid use of `std` altogether? IE, for `isalmostequal` we could do `np.allclose(x, x[0])` and for `islinspaced` could do `np.allclose(np.diff(x), np.diff(x)[0])`

2022-12-17 21:02 UTC, ddudt requested changes
I agree with Rory that the better solution would be to avoid calling `np.std` altogether.

2022-12-17 21:02 UTC, ddudt commented on tests/test_utils.py
> +    zeta_vals = np.unique(grid_small.nodes[:, 2])
can use `zeta_vals = grid.nodes[grid.unique_zeta_idx, 2]`

2022-12-18 02:18 UTC, dpanici commented
addressed the comments. Took me way too long to get a good solution for using `np.allclose` for when the axis may be something other than -1... numpy indexing and broadcasting can be confusing

2022-12-18 05:25 UTC, f0uriest commented on desc/utils.py
> +def isalmostequal(x, axis=-1, rtol=1e-5, atol=1e-8):
should probably tighten these tolerances, otherwise seems fine

2022-12-18 05:25 UTC, f0uriest approved these changes

2022-12-18 18:57 UTC, f0uriest approved these changes

2022-12-18 19:18 UTC, f0uriest submitted a review, later dismissed

2022-12-21 16:32 UTC, ddudt requested changes
This solution seems overly complicated, but it works.

2022-12-21 16:32 UTC, ddudt commented on tests/test_utils.py
> +    assert isalmostequal(np.array(0))
this should be `assert islinspaced(np.array(0))`

2022-12-21 16:32 UTC, ddudt commented on desc/utils.py
> +def isalmostequal(x, axis=-1, rtol=1e-6, atol=1e-12):
need to add `rtol` and `atol` to documentation

2022-12-21 21:44 UTC, dpanici commented
> This solution seems overly complicated, but it works.

yea without np.std I could not figure out how to get the same functionality as cleanly using np.allclose (namely the ability to have the axis of comparison be arbitrary)

2022-12-21 23:13 UTC, f0uriest approved these changes

2022-12-22 16:50 UTC, ddudt approved these changes

2022-12-22 18:36 UTC, merged