Simplify |B| derivative computations
PlasmaControl/DESC pull request #385
Opened 2022-12-30 22:58 UTC by ddudt

Resolves Issue #384 

Also adds some new compute quantities, which may be useful in future applications.

2023-01-02 21:48 UTC, ddudt commented
@unalmis Can you please re-implement the `iota_rr` computation?  Here is your [old implementation](https://github.com/PlasmaControl/DESC/blob/78d0bbec65d37b6d7e25aacbda17d3c55b4feff6/desc/compute/_core.py), it just needs to be updated with our new notation. 

Otherwise all of the new compute quantities are here, all that is left is to add tests for them.

2023-01-03 21:19 UTC, ddudt commented
Can someone please review `TestConstrainCurrent.test_compute_rotational_transform` in `test_constrain_current.py`?  I think this test is supposed to check the iota computations from fixed-current equilibria to their known profiles, but I don't think it's actually doing that.

2023-01-03 22:12 UTC, f0uriest commented on desc/compute/_metric.py
> +    description="Jacobian determinant, second derivative wrt radial coordinate and "
`Jacobian determinant of flux coordinate system`?

2023-01-03 22:13 UTC, f0uriest commented on desc/compute/_metric.py
> +    data["sqrt(g)_r"] = (
why are there 2 things here?

2023-01-04 17:08 UTC, dpanici commented on tests/test_compute_funs.py
> +    np.testing.assert_allclose(
these B, B_r and B_rr don't make sense to me, isn't `B` and `B_r`, `B_rr` the vector magnetic field? so they should not be compared against the magnetic field magnitude's radial derivative? I am unsure how this even is passing the test....

2023-01-04 17:12 UTC, dpanici commented on tests/test_compute_funs.py
>              "|B|",
add vector B field's theta derivatives

2023-01-04 17:12 UTC, dpanici commented on tests/test_compute_funs.py
>              "|B|",
add vector B field's zeta derivatives

2023-01-04 17:49 UTC, unalmis commented
> Can someone please review `TestConstrainCurrent.test_compute_rotational_transform` in `test_constrain_current.py`? I think this test is supposed to check the iota computations from fixed-current equilibria to their known profiles, but I don't think it's actually doing that.

It's supposed to check if `iota` on fixed-iota equilibria (which comes directly from the known profile) is recovered when we force `iota` to be computed via fixed current (the `current` being the surface average of `B_theta` on that same equilibrium).

The test fails if the formula for `iota` is wrong. For example adding a `+ 0.3` to `data["iota_r"]` [here](https://github.com/PlasmaControl/DESC/blob/e7f128fd712c70789685f12e1100046ae88bb0ec/desc/compute/_profiles.py#L341) fails the test.

It should only be a valid test on fixed-iota equilibrium, so I made that change. Good catch

2023-01-04 18:02 UTC, dpanici requested changes
Can we add tests for the magnetic field vector derivatives? should be able to use existing test infrastructure, just need to split the B vectors up into B_R, B_zeta, B_Z by taking `data['B_r'][:,0]1 etc.

2023-01-04 18:55 UTC, dpanici approved these changes

2023-01-05 18:39 UTC, f0uriest commented on variables.csv
> +Name,Label,Units,Description,Module
I think this file is supposed to be `docs/variables.csv`

2023-01-06 02:24 UTC, unalmis approved these changes

2023-01-06 03:18 UTC, dpanici submitted a review, later dismissed
Approved once the variables.csv file is moved to the right spot

2023-01-06 16:54 UTC, f0uriest approved these changes

2023-01-07 03:07 UTC, dpanici approved these changes

2023-01-07 05:33 UTC, merged