Use consistent normalizations when plotting.
PlasmaControl/DESC pull request #481
Opened 2023-04-05 09:54 UTC by f0uriest

- We currently normalize force by either thermal or magnetic pressure
- However, this means that low beta cases can look worse than they really are, since we're normalizing by a small quantity.
- This change makes it so we always use the magnetic pressure, which is well defined and of reasonable magnitude in all cases of interest, and is also consistent with the way we normalize the objective functions

2023-04-05 15:42 UTC, dpanici requested changes
This is ok, a small part of me is unsure of changing it like this bc in my paper all the normalizations/plots were wrt pressure though. Could we add a flag to ask to norm_F by pressure instead of defaulting to always using |B|? Just so I can make comparable plots without needing to rework the plot functions again.

2023-04-05 16:13 UTC, ddudt reviewed
I don't love this idea. The point of normalizing by pressure is to give a percent error for JxB-grad(p). Even in a low beta case, normalizing by pressure still gives a useful relative error metric. Having the option for normalizing by magnetic pressure could be useful to add, but I don't think it should be the default.

2023-04-05 16:13 UTC, ddudt commented on tests/baseline/test_fsa_F_normalized.png
need to change the y limits on this plot

2023-04-05 16:40 UTC, f0uriest commented
The main goal was just to have the normalizing quantity be "smooth" in some sense, instead of jumping from one value to another when we go from vacuum to finite pressure. Another option would be to use the min/max/mean etc of the different terms but that seems more complicated than it's worth.

2023-04-05 23:52 UTC, dpanici commented
@f0uriest yea something like that, so I can do `plot_section(eq,"|F|",norm_F=True, normalize_with_pressure=True)` and just have that flag be False by default

2023-04-06 19:34 UTC, dpanici commented on docs/variables.csv
>  ``(curl(B)xB)_rho``,:math:`((\nabla \times \mathbf{B}) \times \mathbf{B})_{\rho}`,Tesla squared,Covariant radial component of Lorentz force,``desc.compute._field``
missing magnetic tension vol avg entry

2023-04-08 03:55 UTC, dpanici submitted a review, later dismissed

2023-04-11 17:48 UTC, f0uriest commented
Leaving this here for reference:

plotting the different volume averaged pressures for all the equilibria in our examples

![image](https://user-images.githubusercontent.com/22567458/231246524-193f9a1c-f7df-49e3-b228-9f8f6da29531.png)


The two magnetic terms are usually of similar magnitude, and pressure as well when its not zero or really small

2023-04-11 17:50 UTC, ddudt requested changes
Can we have all 3 normalization options? Magnetic pressure gradient can stay as the default, and we already have pressure gradient, so just need to add an option for magnetic tension. Instead of a bunch of flags like `normalize_with_pressure=True` we could use a string like `normalization="pressure"` etc.

2023-04-12 01:14 UTC, dpanici approved these changes

2023-04-12 17:24 UTC, ddudt approved these changes

2023-04-12 20:26 UTC, merged