Add wrapper for user defined objective function
PlasmaControl/DESC pull request #518
Opened 2023-05-30 19:45 UTC by f0uriest

Resolves #185

2023-05-31 00:50 UTC, dpanici submitted a review, later dismissed

2023-05-31 03:03 UTC, unalmis commented on desc/objectives/_generic.py
> +            return variables
well that's neat

2023-05-31 03:03 UTC, unalmis submitted a review, later dismissed

2023-06-01 19:29 UTC, ddudt requested changes
Very cool! Just one minor comment.

2023-06-01 19:29 UTC, ddudt commented on desc/objectives/_generic.py
> +        name="generic",
change to `"custom"`?

2023-06-01 20:23 UTC, ddudt approved these changes

2023-06-02 02:45 UTC, unalmis approved these changes

2023-06-02 07:27 UTC, merged