convert RZCurve to XYZCurve
PlasmaControl/DESC pull request #567
Opened 2023-07-05 14:36 UTC by daniel-dudt

Adds the method `FourierRZCurve.to_xyz(N=None)` to convert to a `FourierXYZCurve`. 

Example use case: converting the magnetic axis to same curve type as coils for plotting, etc. 

Converting the other way (from XYZ to RZ) may not always be possible and is still not implemented.

2023-07-05 15:53 UTC, f0uriest requested changes
This seems fine, only request is I think a better convention for the `to_*` methods is to use the full name of the class (eg `to_FourierXYZCurve`) to avoid ambiguity (eg with Dario's xyz spline curve). I've been meaning to update the profile classes with that but might as well start here.

2023-07-05 15:54 UTC, f0uriest commented
Also converting to an RZ curve should be possible for arbitrary geometries when the generalized toroidal angle is finished.

2023-07-05 18:26 UTC, f0uriest approved these changes

2023-07-10 23:15 UTC, dpanici approved these changes

2023-07-11 17:02 UTC, merged