updating della-gpu installation instructions
PlasmaControl/DESC pull request #576
Opened 2023-07-10 18:17 UTC by rahulgaur104

The current instructions for installing DESC do not seem to work on Della. So, I have used the same instructions as those for Traverse. I am making the same changes as #575 to the master branch. Hopefully, the docs will compile now.

2023-07-10 18:53 UTC, unalmis approved these changes

2023-07-10 18:53 UTC, unalmis commented on docs/installation.rst
On line 194, we should change
```
conda install colorama "h5py>=3.0.0" "matplotlib>=3.3.0,<=3.6.0,!=3.4.3" "mpmath>=1.0.0" "netcdf4>=1.5.4" "numpy>=1.20.0" psutil "scipy>=1.5.0" termcolor
```
to this, where the constrains on numpy and scipy are updated because of the breaking changes they introduced. The other install options already include this change.
```
conda install colorama "h5py>=3.0.0" "matplotlib>=3.3.0,<=3.6.0,!=3.4.3" "mpmath>=1.0.0" "netcdf4>=1.5.4" "numpy>=1.20.0,<1.25.0" psutil "scipy>=1.5.0,<1.11.0" termcolor
```

2023-07-10 19:01 UTC, dpanici commented on docs/installation.rst
you mean for traverse installation?

2023-07-10 19:08 UTC, unalmis commented on docs/installation.rst
yes, although I can't test traverse so I don't know if those traverse-specific instructions still work. My suggestion was assuming it still works

2023-07-10 23:16 UTC, dpanici approved these changes

2023-07-10 23:17 UTC, dpanici requested changes
can you change the last-tested date to today's date?

2023-07-10 23:29 UTC, rahulgaur104 commented on docs/installation.rst
Let me check the present installation instructions for DESC on Traverse.

2023-07-10 23:29 UTC, rahulgaur104 commented
Sure, changing the date to 07/11/23.

2023-07-11 01:39 UTC, rahulgaur104 commented on docs/installation.rst
Kaya, your instructions work without error. I have updated the docs.

2023-07-11 02:26 UTC, unalmis approved these changes

2023-07-11 19:01 UTC, rahulgaur104 commented
I don't know how to enable all the tests. Have you seen this before?

2023-07-11 20:28 UTC, dpanici commented
The tests dont run if only docs have been changed. Sometimes this happens though, just press the bypass button and merge it, it is fine

2023-07-11 20:29 UTC, rahulgaur104 commented
Where is the bypass option?

2023-07-11 20:33 UTC, merged