Ensure two term objective helicity is passed correctly
PlasmaControl/DESC pull request #600
Opened 2023-07-26 16:17 UTC by f0uriest

2023-07-26 17:01 UTC, ddudt requested changes
Can you also make sure that the helicity is handled properly for both `QuasisymmetryBoozer` and `QuasisymmetryTwoTerm`? 

Should this change you made of adding `"helicity"` to the `constants` dict also be made to the Two-Term class? 

Also the Boozer class has the checks:
```
assert len(helicity) == 2
assert (int(helicity[0]) == helicity[0]) and (int(helicity[1]) == helicity[1])
```
but they are missing from the Two-Term class.

2023-07-26 17:12 UTC, f0uriest commented
The checks are in the setter method for both classes, I think the checks in init for the Boozer one are unneeded.

2023-07-26 17:14 UTC, f0uriest commented
We do have tests for the Boozer helicity already, `test_qa_boozer` and `test_qh_boozer`

2023-07-26 19:39 UTC, dpanici approved these changes

2023-07-27 18:21 UTC, ddudt approved these changes

2023-07-27 23:38 UTC, merged