rho grid bug fixes
PlasmaControl/DESC pull request #622
Opened 2023-08-15 18:42 UTC by ddudt

Resolves #619 and also fixes a bug where `PowerSeriesProfile.from_values(sym=True)` did not actually return an even profile.

2023-08-15 19:54 UTC, dpanici requested changes
Can you add a test for the PowerSeriesProfile fix? like just going from SplineProfile to PowerSeries and checking that it is even I mean

2023-08-15 20:35 UTC, f0uriest commented on desc/profiles.py
> +            order = order // 2
I don't think we want to reduce the order here without padding the params later, or passing in the mode numbers explicitly

2023-08-15 20:37 UTC, f0uriest requested changes
I think the even profile fix isn't quite right. Also we should leave #619 open for now, or make a new issue to evaluate the limit properly

2023-08-15 21:41 UTC, ddudt commented on tests/test_profiles.py
> -    @pytest.mark.unit
I deleted this test because it was redundant with `test_close_values`.

2023-08-15 22:15 UTC, f0uriest approved these changes

2023-08-16 15:58 UTC, dpanici approved these changes

2023-08-16 17:17 UTC, merged