fix inconsistency with the equations on the paper
PlasmaControl/DESC pull request #739
Opened 2023-11-07 23:13 UTC by YigitElma

The following equation on the general theory page is not consistent with the one on the paper,

![image](https://github.com/PlasmaControl/DESC/assets/102380275/fbc73493-517f-4011-bd93-cf5e90245b2a)

Maybe in SFL, they might be equivalent, but I am not sure about the Jacobian definition.

<img width="507" alt="image" src="https://github.com/PlasmaControl/DESC/assets/102380275/6ad115cb-269e-4a68-96df-2f86e89209ac">

2023-11-08 00:04 UTC, ddudt commented
The equations in my 2020 paper are outdated, but we should update the documentation if it no longer matches the code. It looks like they do need to be updated now that we are not using SFL coordinates in the code. 

Please keep the sign convention the same, where $F \equiv J \times B - \nabla p$. In your notes it looks like you are using $F \equiv -J \times B + \nabla p$

2023-11-08 03:28 UTC, YigitElma commented
I was looking at DESC code suite part 1.
<img width="665" alt="image" src="https://github.com/PlasmaControl/DESC/assets/102380275/a374f0d8-789e-4460-b78d-3b681d280520">

But ok, you are correct in the code, the force error is calculated in the other way.
<img width="313" alt="image" src="https://github.com/PlasmaControl/DESC/assets/102380275/8151dd9f-51c9-4ca8-bad8-756a4143ed1c">

I will change it. Thanks for pointing it out!

2023-11-08 04:30 UTC, YigitElma commented
Btw, 
![image](https://github.com/PlasmaControl/DESC/assets/102380275/68ed37c2-c5d8-4773-8a12-0b0a0d0c50f4)
This section says that F_helical has jacobian in it, but in the actual calculation of F_helical, there is no jacobian.
![image](https://github.com/PlasmaControl/DESC/assets/102380275/520eb5c5-e611-498e-8edf-2ced5a750abc)
In fact, there is no jacobian in the e^helical either,
![image](https://github.com/PlasmaControl/DESC/assets/102380275/8578b016-902c-4749-85ee-802970c4df65)
This part has Jacobian but I assume it is for dV volume thing
![image](https://github.com/PlasmaControl/DESC/assets/102380275/77efc994-c01b-496a-b4da-7f62e4afac48)

Probably, I miss something. If you want to change the place of jacobian in this PR, let me know please.

2023-11-08 16:10 UTC, dpanici commented
You are looking in my paper Appendix which uses the VMEC notation. in DESC, we define beta without the sqrt(g) (see section 3):
![image](https://github.com/PlasmaControl/DESC/assets/37969854/e5294ef5-803f-4155-8b19-8d94a33627b1)

2023-11-08 16:11 UTC, dpanici requested changes
change to use the notation of section 3 of DESC suite part I (maybe need to change a minus sign to use whatever convention we have for F in the code, I don't remember if my paper is consistent with what we use in the code currently as far as F = JxB - grad(p) or F = grad(p) - JxB

2023-11-08 16:29 UTC, YigitElma commented
@dpanici In the code,  F = JxB - grad(p) is used. I fixed the Jacobian thing.

2023-11-08 18:03 UTC, ddudt reviewed
I made a few edits and I think all of the equations are consistent now.

2023-11-08 18:03 UTC, ddudt commented on docs/theory_general.rst
> +    \mathbf{e}^{helical} &= B^\zeta\mathbf{e}^\theta - B^\theta\mathbf{e}^\zeta
I changed our notation from "beta" to "helical" to match the code. There is a note later on that explains this difference from the original paper.

2023-11-08 18:03 UTC, ddudt commented on docs/theory_general.rst
> +    F_\rho &= \sqrt{g} (J^\theta B^\zeta - J^\zeta B^\theta) - \frac{\partial p}{\partial \rho} \\[.3cm]
Equation (3.26a) in @dpanici's paper has $(J^\zeta B^\theta - J^\theta B^\zeta)$, but I think that is wrong and this equation is correct.

2023-11-09 19:53 UTC, dpanici commented
very confused as to how the unit test compute_everything is failing when this only changed docs...

2023-11-09 20:02 UTC, YigitElma commented
I didn't understand either.

2023-11-09 20:05 UTC, f0uriest commented
> very confused as to how the unit test compute_everything is failing when this only changed docs...

I think its a hardware issue, I fixed it here: https://github.com/PlasmaControl/DESC/pull/735/files#r1382344659

2023-11-10 02:49 UTC, dpanici approved these changes

2023-11-10 02:54 UTC, merged