plot elongation
PlasmaControl/DESC pull request #807
Opened 2023-12-13 03:41 UTC by ddudt

Resolves #804.  

Does the same grid resampling that we do for functions of $\rho$, but now also for $\zeta$. 

The `grid_type` data index tag is no longer used, but I keep it because we should start using this in the future. This PR resolves an issue about plotting functions of $\zeta$ vs $\rho$, but that tag will still be useful for determining the proper type of grid to use (e.g. `"quad"` vs `"linear"`). 

I added a new test and also changed the other 1D plotting tests to get examples so they don't depend on doing an equilibrium solve.

2023-12-13 04:08 UTC, f0uriest commented on tests/test_plotting.py
> +def test_1d_elongation():
is this image missing from the commit?

2023-12-13 04:58 UTC, f0uriest submitted a review, later dismissed

2023-12-13 07:02 UTC, ddudt commented
@unalmis I need your help to make the computation of `"a_major/a_minor"` work on symmetric grids

2024-01-03 20:14 UTC, unalmis commented
> @unalmis I need your help to make the computation of `"a_major/a_minor"` work on symmetric grids

I will work on this now

2024-01-08 21:35 UTC, unalmis commented
@ddudt The computation is working correctly. Here is a jupyter notebook with a visual of what is discussed below [elongation_test.zip](https://github.com/PlasmaControl/DESC/files/13866106/elongation_test.zip). There I confirm the results we compute match the analytic result from sympy.

The reason we are getting a wrong value for `a_major/a_minor` in `test_elongation` on symmetric grids is a resolution issue. The two grids
```python
fg = LinearGrid(L=2, M=eq.M_grid, N=2, sym=False, NFP=eq.NFP)
sg = LinearGrid(L=2, M=eq.M_grid, N=2, sym=True, NFP=eq.NFP)
```
place nodes at different locations in $\theta$. To compute the elongation, we compute a perimeter of a constant $\zeta$ surface by integrating $\Vert \mathbf{e}_{\theta} \Vert$  over $\theta$.  For the particular surface used in `test_elongation`, the quadrature estimates the true integral better when we sample the integrand at the nodes used by `fg` than it does when we sample at the nodes used by `sg`. At reasonable resolution, this difference is not measurable because our midpoint scheme integration will converge to the true integral exponentially on the periodic domain over $\theta$. Increasing `eq.M_grid` from 2 to 4 will pass the test.

As a sanity check , after the fixes in #451 , we can construct a symmetric grid that has the same nodes as `fg` like this:
```python
unique_theta = fg.nodes[fg.unique_theta_idx, 1]
sg_manual = LinearGrid(
    L=2, theta=unique_theta[unique_theta <= np.pi], N=2, sym=True, NFP=eq.NFP
)
```
I have checked computations on `sg_manual` match `fg` at all resolutions.


(some details just for your information: The reason `sg` does not have the same node placement at `sg_manual` is just a design choice:
When a number is passed in for `L, M, N` (or rho, theta, zeta) on `LinearGrid`, we want to construct a grid where all the nodes are weighted equally in any integration etc. The simplest way to do this is to use node placement such that `grid.spacing` and `grid.weights` can be the the same across every node (like it is for `fg`).  When symmetry is set to `true`, it is only correct for `grid.spacing` and `grid.weights` to be the same across every node if the nodes are evenly spaced. This requires that the arc distance between the closest node to $\theta = \pi$ and its reflection across the $\theta = \pi$ axis (let's call this its left neighbor assuming counterclock wise is left) equals the distance to the node to its right. In particular, this means there can't be a node at $\theta = 0$ since that distance is 0, so `sg` must have a different node placement than `fg` in order for `sg.spacing` and `sg.weights` to be constant.

When the node placement is explicitly specified, as in `sg_manual`, it seems important to respect that placement and not change anything. For the grid `sg_manual`,  the attributes `sg.spacing` and  `sg.weights` are not constant - in particular, the nodes at $\theta \neq 0$ have double the weight and spacing as the node at $\theta = 0$ because we need to double count the ones at $\theta \neq 0$  since there would have been two of them if we had not deleted the nodes with $\theta > \pi$. This ensures that all computations on `sg_manual` match those of `fg`.
)


Let me know if there is another potential issue besides  `test_elongation`. As far as I'm aware, the only bug with grids in DESC is if the user gives wants to use grids with duplicate nodes to compute integrals. For example we prioritize correctness of surface integrals over line integrals as mentioned [in the docstring here](https://github.com/PlasmaControl/DESC/blob/b5921fd37016ef13999e5f1157d3ad0931602bc3/desc/compute/utils.py#L676). This could be fixed by creating an alias attribute `grid.line_spacing` that returns `grid.spacing` if there are no duplicate nodes or a different array of shape `(grid.num_nodes, 3)` when there are duplicates.

2024-01-13 23:53 UTC, unalmis approved these changes

2024-01-15 19:46 UTC, dpanici commented
I have a question on how `master_compute_data.pkl` was updated, was the only failing key there the `elongation` and that is why it was updated? did you check that the other keys were still the same?

2024-01-15 20:31 UTC, dpanici requested changes
can you add to the `test_elongation` test function a case where you pass in the override grid, so that that part of the compute logic gets tested? Looks fine otherwise

2024-01-17 17:07 UTC, ddudt commented
> I have a question on how `master_compute_data.pkl` was updated, was the only failing key there the `elongation` and that is why it was updated? did you check that the other keys were still the same?

Yes the only failing key was `elongation`, since the dimension was changed from a scalar to a vector.

2024-01-17 17:09 UTC, ddudt commented
> can you add to the `test_elongation` test function a case where you pass in the override grid, so that that part of the compute logic gets tested? Looks fine otherwise

This is already covered by the `plot_1d` test of elongation. The patch coverage for this PR is 100% according to codecov

2024-01-17 19:44 UTC, dpanici approved these changes

2024-01-17 20:33 UTC, merged