Fix for unused kwargs in Equilibrium init
PlasmaControl/DESC pull request #852
Opened 2024-02-02 19:54 UTC by f0uriest

Resolves #850

2024-02-02 19:56 UTC, unalmis approved these changes

2024-02-02 19:57 UTC, rahulgaur104 approved these changes

2024-02-02 21:10 UTC, dpanici requested changes
update notebooks

2024-02-05 15:30 UTC, dpanici approved these changes

2024-02-06 05:01 UTC, merged