save `buco` and `bvco` on half mesh
PlasmaControl/DESC pull request #870
Opened 2024-02-12 21:00 UTC by ddudt

In `VMECIO.save` we were saving the outputs `buco` and `bvco` on the full mesh, but they should be on the half mesh.

2024-02-12 23:57 UTC, dpanici commented on desc/vmec.py
>          DShear.long_name = "Mercier stability criterion magnetic shear term"
specify mesh

2024-02-12 23:57 UTC, dpanici commented on desc/vmec.py
>          DCurr.long_name = "Mercier stability criterion toroidal current term"
specify mesh

2024-02-12 23:57 UTC, dpanici commented on desc/vmec.py
>          DWell.long_name = "Mercier stability criterion magnetic well term"
specify mesh

2024-02-12 23:57 UTC, dpanici commented on desc/vmec.py
>          DGeod.long_name = "Mercier stability criterion geodesic curvature term"
specify mesh

2024-02-12 23:58 UTC, dpanici requested changes
Looks good, just add to the descriptions of the ones you changed which mesh they are on to be consistent with the other descriptions changed

2024-02-13 00:33 UTC, ddudt commented
> Looks good, just add to the descriptions of the ones you changed which mesh they are on to be consistent with the other descriptions changed

I didn't change the Mercier quantities, but I have now updated their descriptions to say they are saved on the full mesh.

2024-02-13 01:21 UTC, dpanici approved these changes

2024-02-13 01:33 UTC, f0uriest approved these changes

2024-02-13 04:41 UTC, merged